version: '3'


services:
  front:
    build: 
      context: ./../front
      dockerfile: ./../front/front.dockerfile
    restart: always
    ports: 
      - "8090:5000"
    deploy:
      mode: replicated
      replicas: 1
  broker:
    build: 
      context: ./../broker
      dockerfile: ./../broker/broker.dockerfile
    restart: always
    ports: 
      - "8080:80"
    deploy:
      mode: replicated
      replicas: 1
  register: 
    build:
      context: ./../register
      dockerfile: ./../register/register.dockerfile
    restart: always
    ports: 
      - "8081:80"
    deploy:
      mode: replicated
      replicas: 1 
  
