version: '3'


services:
  front:
    build: 
      context: ./../front
      dockerfile: ./../front/front.dockerfile
    restart: always
    ports: 
      - "8090:5000"
    deploy:
      mode: replicated
      replicas: 1
  broker:
    build: 
      context: ./../broker
      dockerfile: ./../broker/broker.dockerfile
    restart: always
    ports: 
      - "8080:80"
    deploy:
      mode: replicated
      replicas: 1
  register: 
    build:
      context: ./../register
      dockerfile: ./../register/register.dockerfile
    restart: always
    ports: 
      - "8081:80"
    deploy:
      mode: replicated
      replicas: 1 
    environment:
      DSN: "host=postgres port=5432 user=postgres password=password dbname=users sslmode=disable timezone=UTC connect_timeout=5"
  
  postgres:
    image: 'postgres:15.2'
    ports:
      - "5432:5432"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: users
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/

  pgadmin4:
    image: dpage/pgadmin4
    ports: 
      - "8091:80"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      PGADMIN_DEFAULT_EMAIL: "dani@abv.bg" 
      PGADMIN_DEFAULT_PASSWORD: "password"

