# permissions for end users to view appversions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: api-operator
    app.kubernetes.io/managed-by: kustomize
  name: appversion-viewer-role
rules:
- apiGroups:
  - apps.bankingcircle.net.bankingcircle.net
  resources:
  - appversions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps.bankingcircle.net.bankingcircle.net
  resources:
  - appversions/status
  verbs:
  - get
