---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - apps.bankingcircle.net.bankingcircle.net
  resources:
  - appversions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.bankingcircle.net.bankingcircle.net
  resources:
  - appversions/finalizers
  verbs:
  - update
- apiGroups:
  - apps.bankingcircle.net.bankingcircle.net
  resources:
  - appversions/status
  verbs:
  - get
  - patch
  - update
