FROM golang:1.20-alpine3.18 AS build
RUN apk add --no-cache git
WORKDIR /tmp/app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go test -v
RUN GO build -o ./out/holidayreservation ./cmd/app/*.go 


FROM alpine:3.18.0
RUN apk add ca-certificates
COPY --from=build /tmp/app/out/holidayreservation /app/holidayreservation
CMD [ "/app/holudayreservation" ]