apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: todo-postgresql-data
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  accessModes: [ReadWriteOnce]
  resources: { requests: { storage: 1Gi } }