apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "redis.fullname" . }}-pvc
  labels:
    {{- include "redis.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: zrs-managed-csi-premium
  resources:
    requests:
      storage: 5Gi
