apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: some-demo
  namespace: argocd

spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: 'demo-argo'
    server: '*'
  sourceRepos:
    - '*'
