apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
 

resources:
- ../base


patchesStrategicMerge:
- cm-example.yaml



images:
- name: ghcr.io/dkr290/go-projects/todofiber
  newTag: 5dda076b
- name: ghcr.io/dkr290/go-projects/postgres
  newTag: 5dda076b

commonAnnotations:
  todofiber/version: v1.2