version: '3'
services:
  mysql:
    image: mysql:5.6.27
    ports:
      - "3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d  
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      TZ: Europe/Luxembourg

  cloudbeaver:
    image: dbeaver/cloudbeaver:latest
    ports: 
      - "8080:8978"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      CB_ADMIN_NAME: cbadmin
      CB_ADMIN_PASSWORD: Password123
    volumes:
      - cloudbeaverdata:/opt/cloudbeaver/workspace

volumes:
  mysqldata:
    driver: local
  cloudbeaverdata:
    driver: local