up:
	@echo "Starting Docker images..."
	docker compose up -d
	@echo "Docker images started!"


down:
	@echo "Stopping docker compose..."
	docker compose down
	@echo "Done!"

stop:
	@echo "Stopping docker compose..."
	docker compose stop
	@echo "Done!"

start:
	@echo "Starting docker compose..."
	docker compose start
	@echo "Done!"