apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: todo-postgresql    
  name: todo-postgresql
 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-postgresql
  strategy:
    type: Recreate
      
  template:
    metadata:
      labels:
        app: todo-postgresql
        
    spec:
      initContainers:
      - name: take-data-dir-ownership
        image:  alpine:3.16.2
        command: ['sh', '-c','chmod 777 /bitnami/postgresql' ]

        
        volumeMounts:
        - name: postgresql-data
          mountPath: "/bitnami/postgresql"
     
      containers:
      - image: bitnami/postgresql:latest
        name: postgresql
       
        env:
        - name: POSTGRESQL_USERNAME
          valueFrom:
            secretKeyRef:
              name: dbusecret
              key: database-user
        - name: POSTGRESQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: dbusecret
              key: database-pass
        resources:
          limits:
            memory: "1Gi"
            cpu: "0.5"
          requests:
            memory: 512Mi
            cpu: "0.2"
        volumeMounts:
        - name: postgresql-data
          mountPath: "/bitnami/postgresql"
     
      restartPolicy: Always
      volumes:
      - name: postgresql-data
        persistentVolumeClaim:
          claimName: "todo-postgresql-data"
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-db-svc
spec:
  ports:
    - name: "5432"
      port: 5432
      targetPort: 5432
      protocol: TCP
  type: ClusterIP
  selector:
    app: todo-postgresql 

