apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: todo-postgresql-data
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: managed-csi-premium
  resources:
    requests:
      storage: 1Gi