namePreffix: todofiber-


apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- todofiber.yaml




images:
- name: ghcr.io/dkr290/go-projects/todofiber:8bb3c774
#  newTag: 8bb3c774