apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
 


bases:
- ../../base

patchesStrategicMerge:
- cm.example.yaml

images:
- name: ghcr.io/dkr290/go-projects/todofiber
  newTag: latest
- name: ghcr.io/dkr290/go-projects/postgres
  newTag: latest

commonAnnotations:
  todofiber/version: v1.3
